language: perl

install:

script: prove -v t

perl:
  - "5.6"
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "6.14"
  - "0"
  - "-1"
  - "0.10"
  - "-1.10"
  - "asdf"
  - "123; ls; who"
